# Generated by Django 4.2 on 2023-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('logo_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brands',
                'managed': True,
            },
        ),
    ]
