# Generated by Django 4.2 on 2023-04-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_productquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answers_date', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.productquestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.products')),
            ],
            options={
                'db_table': 'product_answers',
                'managed': True,
            },
        ),
    ]
