# Generated by Django 4.2 on 2023-04-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_orders_optionvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(max_length=255)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('unknown', 'UNKNOWN')], default=('unknown', 'UNKNOWN'))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.orders')),
            ],
            options={
                'db_table': 'payments',
                'managed': True,
            },
        ),
    ]
