# Generated by Django 4.2 on 2023-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0013_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='newsletter_subscription',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
