# Generated by Django 4.2 on 2023-04-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_alter_users_newsletter_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='url',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture_url',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
