# Generated by Django 4.2 on 2023-04-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0015_alter_productimages_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='logo_url',
            field=models.ImageField(null=True, upload_to='logo_images/'),
        ),
    ]
