# Generated by Django 4.2 on 2023-04-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0017_alter_categories_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount_type',
            field=models.CharField(choices=[('percentage discount', 'P_DISCOUNT'), ('fixed cart discounts', 'FC_DISCOUNT'), ('fixed product discounts', 'FP_DISCOUNT')]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('failed', 'FAILED'), ('refunded', 'REFUNDED'), ('unknown', 'UNKNOWN')], default=('unknown', 'UNKNOWN')),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_status',
            field=models.TextField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default=('inactive', 'INACTIVE')),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=('male', 'MALE'), max_length=20),
        ),
    ]
